#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-build}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK_ROOT="${XTOOL_WINDOWS_TCC_WORK:-$ROOT/.build/mobile-windows-tcc}"
SRC_ROOT="$WORK_ROOT/src"
TCC_SRC="$SRC_ROOT/tinycc"
BUILD_ROOT="$WORK_ROOT/build"
GEN_ROOT="$BUILD_ROOT/generated"
PACKAGE_ROOT="$WORK_ROOT/package"
BACKEND_DYLIB="$PACKAGE_ROOT/libXToolWindowsTCC.dylib"

# Pin the source so XTool's backend is reproducible.
TCC_REPOSITORY="${XTOOL_TCC_REPOSITORY:-https://github.com/TinyCC/tinycc.git}"
TCC_COMMIT="${XTOOL_TCC_COMMIT:-0fb54300b56512754221d80adda85ddb9815bceb}"

DARWIN_ROOT="${DARWIN_SDK_ROOT:-$HOME/.swiftpm/swift-sdks/darwin.artifactbundle}"
IOS_PLATFORM="$DARWIN_ROOT/Developer/Platforms/iPhoneOS.platform"
DEPLOYMENT="${XTOOL_IOS_DEPLOYMENT_TARGET:-16.0}"
TARGET="arm64-apple-ios${DEPLOYMENT}"

section() { printf '\n=== %s ===\n' "$1"; }
die() { echo "error: $*" >&2; exit 1; }

find_exec() {
  local name="$1"; shift
  local candidate
  for candidate in "$@"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  die "$name not found"
}

IOS_SDK=""
if [[ -d "$IOS_PLATFORM/Developer/SDKs" ]]; then
  IOS_SDK="$(find "$IOS_PLATFORM/Developer/SDKs" -maxdepth 1 -type d -name 'iPhoneOS*.sdk' | sort -V | tail -1 || true)"
fi
[[ -n "$IOS_SDK" ]] || die "iPhoneOS SDK not found under $IOS_PLATFORM/Developer/SDKs"

CLANG="$(find_exec clang \
  /opt/swift/usr/bin/clang \
  /usr/bin/clang \
  /data/data/com.termux/files/usr/bin/clang \
  "$(command -v clang 2>/dev/null || true)")"

prepare_source() {
  mkdir -p "$SRC_ROOT"

  if [[ ! -d "$TCC_SRC/.git" ]]; then
    rm -rf "$TCC_SRC"
    echo "Cloning TinyCC..."
    git -c http.version=HTTP/1.1 clone --filter=blob:none --no-checkout \
      "$TCC_REPOSITORY" "$TCC_SRC"
  fi

  if [[ "$(git -C "$TCC_SRC" rev-parse HEAD 2>/dev/null || true)" != "$TCC_COMMIT" ]]; then
    echo "Checking out pinned TinyCC $TCC_COMMIT ..."
    git -C "$TCC_SRC" fetch --depth 1 origin "$TCC_COMMIT"
    git -C "$TCC_SRC" checkout --detach "$TCC_COMMIT"
  fi

  echo "TinyCC: $(git -C "$TCC_SRC" rev-parse --short=12 HEAD)"
}

generate_config() {
  mkdir -p "$GEN_ROOT" "$PACKAGE_ROOT"
  local version
  version="$(cat "$TCC_SRC/VERSION" 2>/dev/null || echo unknown)"

  # This is deliberately a host configuration, not a target configuration.
  # The target is supplied separately with TCC_TARGET_X86_64 + TCC_TARGET_PE.
  # Do not define TCC_TARGET_ARM64 or TCC_TARGET_MACHO here: the dylib itself is
  # arm64 iOS, while the compiler it contains emits x86_64 Windows PE code.
  cat > "$GEN_ROOT/config.h" <<EOF
/* Generated by XTool's minimal TinyCC backend build. */
#ifndef XTOOL_TINYCC_CONFIG_H
#define XTOOL_TINYCC_CONFIG_H
#define TCC_VERSION "$version"
#define CC_NAME CC_clang
#define GCC_MAJOR 4
#define GCC_MINOR 2
#define CONFIG_TCC_STATIC 1
#define CONFIG_TCC_BACKTRACE 0
#define CONFIG_TCC_BCHECK 0
#define CONFIG_TCC_PREDEFS 0
#define CONFIG_TCC_SEMLOCK 1
#define CONFIG_TCCDIR "."
#define CONFIG_TCC_SYSINCLUDEPATHS "{B}/include:{B}/include/winapi"
#define CONFIG_TCC_LIBPATHS "{B}/lib"
#define CONFIG_TCC_CRTPREFIX "{B}/lib"
#define CONFIG_TCC_CROSSPREFIX "x86_64-win32-"
#define CONFIG_TCC_ELFINTERP "-"
#endif
EOF
}

find_macho_linker() {
  local candidate
  if [[ -n "${XTOOL_MACHO_LINKER:-}" && -x "${XTOOL_MACHO_LINKER}" ]]; then
    printf '%s' "$XTOOL_MACHO_LINKER"
    return 0
  fi

  for candidate in \
    "$ROOT/.build/mobile-compiler-engine/host-tblgen/bin/ld64.lld" \
    /opt/swift/usr/bin/ld64.lld \
    /usr/bin/ld64.lld \
    /data/data/com.termux/files/usr/bin/ld64.lld \
    "$(command -v ld64.lld 2>/dev/null || true)"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  return 1
}

build_backend() {
  prepare_source
  generate_config
  mkdir -p "$BUILD_ROOT" "$PACKAGE_ROOT"

  section "TinyCC Windows backend"
  echo "host dylib:          $TARGET"
  echo "generated target:    x86_64 Windows PE64"
  echo "TinyCC commit:       $TCC_COMMIT"
  echo "SDK:                  $IOS_SDK"
  echo "heavy build graph:    NONE"
  echo "compile units:        2 C objects + 1 dylib link"
  echo "LLVM/Clang rebuild:   NONE"

  local common=(
    --target="$TARGET"
    -isysroot "$IOS_SDK"
    -fPIC
    -O2
    -std=gnu11
  )

  echo "[1/3] compiling TinyCC one-source x86_64 PE backend..."
  "$CLANG" "${common[@]}" \
    -I"$GEN_ROOT" \
    -I"$TCC_SRC" \
    -DONE_SOURCE=1 \
    -DTCC_TARGET_X86_64=1 \
    -DTCC_TARGET_PE=1 \
    -DCONFIG_TCC_STATIC=1 \
    -c "$TCC_SRC/libtcc.c" \
    -o "$BUILD_ROOT/libtcc-x86_64-pe.o"

  echo "[2/3] compiling XTool TinyCC bridge..."
  "$CLANG" "${common[@]}" \
    -I"$TCC_SRC" \
    -I"$ROOT/WindowsTCCBackend/include" \
    -DXTOOL_WINDOWS_TCC_VERSION='"tinycc-0fb54300-x86_64-pe"' \
    -c "$ROOT/WindowsTCCBackend/XToolWindowsTCC.c" \
    -o "$BUILD_ROOT/XToolWindowsTCC.o"

  local macho_linker=""
  macho_linker="$(find_macho_linker || true)"
  local link_driver=()
  if [[ -n "$macho_linker" ]]; then
    link_driver+=(--ld-path="$macho_linker")
  fi

  echo "[3/3] linking arm64 iOS backend dylib..."
  "$CLANG" --target="$TARGET" -isysroot "$IOS_SDK" -dynamiclib \
    "${link_driver[@]}" \
    "$BUILD_ROOT/libtcc-x86_64-pe.o" \
    "$BUILD_ROOT/XToolWindowsTCC.o" \
    -Wl,-arch,arm64 \
    -Wl,-platform_version,ios,"$DEPLOYMENT","$DEPLOYMENT" \
    -Wl,-syslibroot,"$IOS_SDK" \
    -Wl,-install_name,@rpath/libXToolWindowsTCC.dylib \
    -o "$BACKEND_DYLIB"

  section "result"
  [[ -f "$BACKEND_DYLIB" ]] || die "link completed but backend is missing: $BACKEND_DYLIB"
  file "$BACKEND_DYLIB" 2>/dev/null || true
  du -h "$BACKEND_DYLIB" | awk '{print "size: "$1}'
  echo "SUCCESS: $BACKEND_DYLIB"
  echo "Next phase: load this dylib in XTool and compile HelloWin.c -> HelloWin.exe."
}

show_status() {
  section "TinyCC Windows backend status"
  echo "work root: $WORK_ROOT"
  echo "pinned TinyCC: $TCC_COMMIT"
  if [[ -f "$BACKEND_DYLIB" ]]; then
    echo "backend: $BACKEND_DYLIB"
    file "$BACKEND_DYLIB" 2>/dev/null || true
    du -h "$BACKEND_DYLIB" | awk '{print "size: "$1}'
  else
    echo "backend: not built"
  fi
}

clean_backend() {
  rm -rf "$BUILD_ROOT" "$PACKAGE_ROOT"
  echo "Removed TinyCC backend build outputs; source checkout kept at $TCC_SRC"
}

case "$MODE" in
  prepare) prepare_source; generate_config ;;
  build) build_backend ;;
  status) show_status ;;
  clean) clean_backend ;;
  *) echo "usage: $0 [prepare|build|status|clean]" >&2; exit 2 ;;
esac
