#!/usr/bin/env python3
"""Export a successfully resolved/built SwiftPM iOS product for XTool Mobile.

SwiftPM evaluates manifests and runs generators on the host. Swift source modules
are rebuilt on iPad; native dependency objects are carried over from the host.
Only the Python standard library is required. Never executes anything on iPad.
"""
import argparse
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import struct
import subprocess
import sys


def run(args, cwd):
    return subprocess.run(args, cwd=cwd, check=True, text=True, stdout=subprocess.PIPE).stdout


def dependency_order(root, commands, dependencies):
    visiting, done, order = set(), set(), []
    def visit(name):
        if name in done or name not in commands:
            return
        if name in visiting:
            raise ValueError(f"Dependency cycle: {name}")
        visiting.add(name)
        for dep in dependencies.get(name, []):
            visit(dep)
        visiting.remove(name)
        done.add(name)
        order.append(name)
    if root not in commands:
        raise ValueError(f"No Swift compile command for {root}; use --target to select the executable module")
    visit(root)
    return order


class Inputs:
    def __init__(self, output, project, build, sdk, resources):
        self.output, self.project, self.build = output, project, build
        self.sdk, self.resources = sdk, resources
        self.copied = set()
        self.text_files = set()
        self.originals = {}

    def destination(self, path):
        path = Path(os.path.abspath(path))
        for base, prefix in [(self.build, "PreparedBuild"), (self.project, "Project")]:
            if path.is_relative_to(base):
                return Path(prefix) / path.relative_to(base)
        # External local packages retain a unique absolute-path namespace.
        return Path("External") / path.relative_to(path.anchor)

    def copy(self, path):
        path = Path(os.path.abspath(path))
        if not path.exists():
            raise ValueError(f"Build input is missing: {path}")
        relative = self.destination(path)
        destination = self.output / relative
        if path in self.copied:
            return relative.as_posix()
        self.copied.add(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if path.is_dir():
            def ignore(directory, names):
                return [name for name in names if name in ('.git', '.build', '__pycache__')
                        or name.endswith('.pcm') or Path(directory) / name == self.output]
            shutil.copytree(path, destination, dirs_exist_ok=True, symlinks=False,
                            ignore=ignore)
            for copied in destination.rglob('*'):
                if copied.suffix in ('.modulemap', '.h', '.hpp'):
                    self.text_files.add(copied)
                    self.originals[copied] = path / copied.relative_to(destination)
        else:
            shutil.copy2(path, destination, follow_symlinks=True)
            if destination.suffix in ('.modulemap', '.h', '.hpp'):
                self.text_files.add(destination)
                self.originals[destination] = path
        return relative.as_posix()

    def path_argument(self, value):
        path = Path(os.path.abspath(value))
        platform_lib = self.sdk.parent.parent / 'usr/lib'
        for base, replacement in [(self.resources, '${SWIFT_RESOURCES}'), (self.sdk, '${SDK}'),
                                  (platform_lib, '${SDK}/../../usr/lib')]:
            # SDK version aliases must be checked before resolving symlinks.
            if path.is_relative_to(base):
                return replacement + '/' + path.relative_to(base).as_posix()
            if path.resolve().is_relative_to(base.resolve()):
                return replacement + '/' + path.resolve().relative_to(base.resolve()).as_posix()
        if path == self.build / 'Modules':
            return '${BUILD}/Modules'
        return '${PROJECT}/' + self.copy(path)

    def finish_modulemaps(self):
        # Module maps generated by SwiftPM can contain absolute umbrella headers.
        # Make those paths relative to the copied module map, not the host.
        processed = set()
        while self.text_files - processed:
            file = (self.text_files - processed).pop()
            processed.add(file)
            if file.suffix != '.modulemap':
                continue
            text = file.read_text()
            def replace(match):
                original = Path(match.group(2))
                if not original.is_absolute():
                    original = self.originals[file].parent / original
                copied = self.output / self.copy(original)
                return match.group(1) + '"' + os.path.relpath(copied, file.parent).replace(os.sep, '/') + '"'
            file.write_text(re.sub(r'((?:umbrella\s+header|umbrella|header)\s+)"([^"\n]+)"', replace, text))


def frontend_flags(frontend, sources, inputs):
    """Retain the real driver's semantic flags; replace host outputs and paths."""
    result = []
    source_set = set(map(str, sources))
    discard_values = {
        '-o', '-target', '-sdk', '-resource-dir', '-module-name', '-emit-module-path',
        '-emit-module-doc-path', '-emit-module-source-info-path', '-emit-dependencies-path',
        '-emit-reference-dependencies-path', '-serialize-diagnostics-path', '-emit-abi-descriptor-path',
        '-module-cache-path', '-sdk-module-cache-path', '-prebuilt-module-cache-path',
        '-target-sdk-version', '-target-sdk-name', '-index-store-path', '-index-unit-output-path',
        '-external-plugin-path', '-plugin-path', '-in-process-plugin-server-path',
        '-num-threads', '-module-load-mode', '-file-compilation-dir', '-file-prefix-map',
        '-entry-point-function-name',
    }
    path_values = {'-I', '-F', '-Fsystem', '-import-objc-header', '-vfsoverlay'}
    a = list(frontend)
    i = 0
    while i < len(a):
        arg = a[i]
        i += 1
        if arg in ('-frontend', '-c', '-scan-dependencies', '-primary-file', '-whole-module-optimization',
                   '-enable-batch-mode', '-incremental', '-emit-dependencies', '-emit-module', '-g'):
            continue
        if arg in source_set:
            continue
        if arg in discard_values:
            i += 1
            continue
        if arg.startswith(('-load-plugin-', '-explicit-swift-module-map-file')):
            raise ValueError(f"Module needs unsupported runtime macro/explicit-module inputs: {arg}")
        if arg in path_values:
            result += [arg, inputs.path_argument(a[i])]
            i += 1
            continue
        if arg == '-Xcc':
            value = a[i]
            i += 1
            # Clang's paths are often joined in SwiftPM's invocation.
            matched = False
            for prefix in ('-fmodule-map-file=', '-I', '-F', '-isystem', '-iquote'):
                if value.startswith(prefix) and len(value) > len(prefix):
                    result += ['-Xcc', prefix + inputs.path_argument(value[len(prefix):])]
                    matched = True
                    break
            if matched:
                continue
            if value.startswith(('-fdebug-compilation-dir=', '-fcoverage-compilation-dir=')):
                continue
            if value in ('-I', '-F', '-isystem', '-iquote', '-isysroot'):
                if i + 1 >= len(a) or a[i] != '-Xcc':
                    raise ValueError(f"Unexpected Clang path argument after {value}")
                result += ['-Xcc', value, '-Xcc', inputs.path_argument(a[i + 1])]
                i += 2
                continue
            result += ['-Xcc', value]
            continue
        if arg.startswith('/'):
            raise ValueError(f"Unmapped absolute compiler argument: {arg}")
        result.append(arg)
    return result


def macho_dependencies(executable):
    """Read dependency install names from a thin arm64 Mach-O, without otool."""
    with open(executable, 'rb') as f:
        header = f.read(32)
        if len(header) != 32:
            raise ValueError('Built product has no Mach-O header')
        magic, cpu, _, kind, count, size, _, _ = struct.unpack('<8I', header)
        if (magic, cpu, kind) != (0xfeedfacf, 0x100000c, 2):
            raise ValueError('Export needs a thin arm64 iOS executable from a successful cross-build')
        commands = f.read(size)
    names, offset = [], 0
    for _ in range(count):
        cmd, length = struct.unpack_from('<II', commands, offset)
        if length < 8 or offset + length > len(commands):
            raise ValueError('Invalid Mach-O load commands')
        if cmd in (0xc, 0x80000018, 0x8000001f):
            start = struct.unpack_from('<I', commands, offset + 8)[0]
            names.append(commands[offset + start:offset + length].split(b'\0')[0].decode())
        offset += length
    return names


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project', type=Path, default=Path.cwd())
    parser.add_argument('--product', default='XToolMobileApp')
    parser.add_argument('--target')
    parser.add_argument('--bundle-id', default='com.example.xtoolmobile')
    parser.add_argument('--deployment-target', default='16.0')
    parser.add_argument('--configuration', default='debug', choices=['debug', 'release'])
    parser.add_argument('--swift-sdk', default='arm64-apple-ios')
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--skip-build', action='store_true', help='Use an existing successful host build')
    parser.add_argument('--zip', action='store_true', help='Also create a ZIP to transfer and extract in iPad Files')
    parser.add_argument('--framework', action='append', default=[])
    parser.add_argument('--library', action='append', default=[])
    parser.add_argument('--link-file', action='append', default=[])
    args = parser.parse_args()
    project, output = args.project.resolve(), args.output.resolve()
    if output.exists():
        raise ValueError(f'Output already exists; choose a new folder: {output}')
    if args.zip and Path(str(output) + '.zip').exists():
        raise ValueError(f'ZIP already exists: {output}.zip')
    swift = os.environ.get('XTOOL_HOST_SWIFTC', shutil.which('swiftc') or 'swiftc')
    swift_tool = str(Path(swift).with_name('swift')) if Path(swift).is_absolute() else 'swift'
    build_args = [swift_tool, 'build', '--product', args.product, '--swift-sdk', args.swift_sdk, '-c', args.configuration]
    if not args.skip_build:
        subprocess.run(build_args, cwd=project, check=True)
    build = Path(run(build_args + ['--show-bin-path'], project).strip()).resolve()
    description = json.loads((build / 'description.json').read_text())
    commands = {c['moduleName']: c for c in description.get('swiftCommands', {}).values()}
    if not commands:
        # Integrated-driver builds still record every module's full scan invocation.
        for name, scan in description.get('swiftTargetScanArgs', {}).items():
            sources = [p for p in scan if p.endswith('.swift') and Path(p).is_file()]
            if sources:
                commands[name] = {'moduleName': name, 'scan': scan, 'sources': sources, 'objects': []}
    target = args.target or args.product
    dependencies = description.get('targetDependencyMap', {})
    order = dependency_order(target, commands, dependencies)
    executable = build / args.product
    install_names = macho_dependencies(executable)
    print(f'Preparing {len(order)} Swift modules from {build}')
    output.mkdir(parents=True)
    try:
        inputs = None
        targets = []
        swift_objects = set()
        for name in order:
            print(f'Exporting {name} ...', flush=True)
            command = commands[name]
            sources = [Path(p) for p in command['sources']]
            if 'scan' in command:
                driver = command['scan'][1:]
                cleaned, i = [], 0
                while i < len(driver):
                    if driver[i] == '-driver-use-frontend-path':
                        i += 2
                    elif driver[i] in ('-scan-dependencies', '-c', '-incremental', '-enable-batch-mode'):
                        i += 1
                    else:
                        cleaned.append(driver[i]); i += 1
                invocation = [swift, '-###', '-c', '-whole-module-optimization'] + cleaned
            else:
                invocation = [swift, '-###', '-c', '-whole-module-optimization', '-module-name', name]
                if command.get('isLibrary'):
                    invocation.append('-parse-as-library')
                for original, alias in (command.get('moduleAliases') or {}).items():
                    invocation += ['-module-alias', f'{original}={alias}']
                invocation += list(map(str, sources)) + ['-I', str(build / 'Modules')]
                invocation += command.get('otherArguments', [])
            result = subprocess.run(invocation, cwd=project, text=True, capture_output=True, check=True)
            jobs = []
            for line in (result.stdout + '\n' + result.stderr).splitlines():
                try:
                    words = shlex.split(line)
                except ValueError:
                    continue
                if '-frontend' in words and '-c' in words:
                    jobs.append(words)
            if len(jobs) != 1:
                raise ValueError(f'{name}: expected one whole-module frontend job, found {len(jobs)}; inspect swiftc -### output')
            job = jobs[0][1:]
            def option(flag): return job[job.index(flag) + 1]
            if inputs is None:
                inputs = Inputs(output, project, build, Path(option('-sdk')), Path(option('-resource-dir')))
            if not option('-target').startswith('arm64-apple-ios'):
                raise ValueError(f'{name}: host tools/macros cannot be exported as iOS modules')
            flags = frontend_flags(job, sources, inputs)
            targets.append({'name': name, 'sources': [inputs.copy(p) for p in sources],
                            'dependencies': [d for d in dependencies.get(name, []) if d in order],
                            'swiftFlags': flags,
                            'parseAsLibrary': '-parse-as-library' in job})
            swift_objects.update(Path(p).resolve() for p in command.get('objects', []))
            # Integrated-driver descriptions may not list objects explicitly.
            swift_objects.update(p.resolve() for p in (build / f'{name}.build').glob('*.o'))
        file_list = build / f'{args.product}.product/Objects.LinkFileList'
        if not file_list.is_file():
            raise ValueError(f'Product object list missing: {file_list}')
        link_inputs = shlex.split(file_list.read_text()) + args.link_file
        native = [Path(p).resolve() for p in link_inputs if Path(p).resolve() not in swift_objects]
        for path in native:
            if path.suffix not in ('.o', '.a'):
                raise ValueError(f'Unexpected native link input: {path}')
        resources = []
        for bundle in build.glob('*.bundle'):
            resources.append({'path': inputs.copy(bundle), 'destination': bundle.name})
        frameworks, libraries = set(args.framework), set(args.library)
        for install in install_names:
            if install.startswith('/System/Library/Frameworks/'):
                frameworks.add(install.split('/')[4].removesuffix('.framework'))
            elif install.startswith('/usr/lib/'):
                name = Path(install).name.removeprefix('lib').removesuffix('.dylib')
                if name not in ('System.B', 'objc.A', 'c++', 'c++.1'):
                    libraries.add(name)
            elif install.startswith('@rpath/'):
                library = build / install.removeprefix('@rpath/')
                if not library.is_file():
                    raise ValueError(f'Dynamic dependency must be supplied in build directory: {install}')
                resources.append({'path': inputs.copy(library), 'destination': 'Frameworks/' + library.name})
            else:
                raise ValueError(f'Unsupported dependency install name: {install}')
        manifest = {'schemaVersion': 1, 'name': args.product, 'bundleIdentifier': args.bundle_id,
                    'deploymentTarget': args.deployment_target, 'executableTarget': target, 'targets': targets,
                    'linkFiles': [inputs.copy(p) for p in native], 'frameworks': sorted(frameworks),
                    'libraries': sorted(libraries), 'resources': resources}
        if args.product == 'XToolMobileApp':
            manifest.update(reuseCompilerEngine=True, reuseBundledRuntime=True)
        inputs.finish_modulemaps()
        if (project / 'Package.resolved').is_file():
            shutil.copy2(project / 'Package.resolved', output / 'Package.resolved')
        (output / 'Preparation.txt').write_text(
            f'Product: {args.product}\nHost: {run([swift, "--version"], project)}\n'
            f'Swift source modules: {len(targets)}\nPrebuilt native link inputs: {len(native)}\n'
            'Dependencies and generated sources are frozen at preparation time.\n'
            'Package manifest changes, native dependency changes and generator changes require preparation again.\n'
        )
        (output / 'xtool-mobile.json').write_text(json.dumps(manifest, indent=2) + '\n')
        if args.zip:
            archive = shutil.make_archive(str(output), 'zip', root_dir=output.parent, base_dir=output.name)
            print(f'Transfer archive: {archive}')
        print(f'Ready: {output}\nImport this folder in XTool Mobile, then Build Unsigned IPA.')
    except Exception:
        # Preserve diagnostics/partial inputs for inspection; never mark a failed export usable.
        (output / 'xtool-mobile.json').unlink(missing_ok=True)
        raise


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        sys.exit(f'error: {error}')
