import Foundation

/// The subset of a Swift SDK definition needed by XTool's in-process frontend.
///
/// The desktop/Linux xtool build already succeeds with the Darwin Swift SDK
/// generated by SDKBuilder. Mobile reuses the same paths instead of guessing a
/// minimal frontend layout.
public struct MobileSwiftSDKConfiguration: Sendable, Hashable {
    public let sdkURL: URL
    public let swiftResourceDirectory: URL
    public let includeSearchPaths: [URL]
    public let librarySearchPaths: [URL]
    public let clangBuiltinHeaders: URL?
    public let cameFromSwiftSDKMetadata: Bool

    public init(
        sdkURL: URL,
        swiftResourceDirectory: URL,
        includeSearchPaths: [URL],
        librarySearchPaths: [URL],
        clangBuiltinHeaders: URL?,
        cameFromSwiftSDKMetadata: Bool
    ) {
        self.sdkURL = sdkURL
        self.swiftResourceDirectory = swiftResourceDirectory
        self.includeSearchPaths = includeSearchPaths
        self.librarySearchPaths = librarySearchPaths
        self.clangBuiltinHeaders = clangBuiltinHeaders
        self.cameFromSwiftSDKMetadata = cameFromSwiftSDKMetadata
    }

    /// Canonical platform-specific Swift resource directory. Apple toolchains
    /// place serialized iPhoneOS modules here, while the SDK also carries
    /// textual fallback interfaces under <sdk>/usr/lib/swift.
    public var iPhoneOSSwiftResourceDirectory: URL {
        swiftResourceDirectory.appendingPathComponent("iphoneos", isDirectory: true)
    }

    /// Version encoded by an SDK name such as iPhoneOS26.5.sdk.
    public var targetSDKVersion: String? {
        let stem = sdkURL.deletingPathExtension().lastPathComponent
        let prefix = "iPhoneOS"
        guard stem.hasPrefix(prefix) else { return nil }
        let version = String(stem.dropFirst(prefix.count))
        if !version.isEmpty { return version }

        let settingsURL = sdkURL.appendingPathComponent("SDKSettings.json")
        guard let data = try? Data(contentsOf: settingsURL),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let settingsVersion = object["Version"] as? String,
              !settingsVersion.isEmpty else {
            return nil
        }
        return settingsVersion
    }

    /// XTool's serialized stdlib cache built by the matching upstream Swift
    /// compiler on the Linux host. This must be passed explicitly to frontend
    /// invocations; simply placing it under the resource directory does not make
    /// FrontendTool discover this nonstandard cache automatically.
    public var xtoolPrebuiltModuleCacheDirectory: URL? {
        guard let version = targetSDKVersion else { return nil }
        return iPhoneOSSwiftResourceDirectory
            .appendingPathComponent("xtool-prebuilt-modules", isDirectory: true)
            .appendingPathComponent(version, isDirectory: true)
    }

    /// Canonical SDK name normally synthesized by the Swift driver.
    public var targetSDKName: String? {
        guard let version = targetSDKVersion else { return nil }
        return "iphoneos\(version)"
    }
}

public extension PreparedToolchain {
    var swiftSDKMetadataURL: URL {
        root.appendingPathComponent("swift-sdk.json")
    }

    var hasSwiftSDKMetadata: Bool {
        FileManager.default.fileExists(atPath: swiftSDKMetadataURL.path)
    }

    /// Resolve the exact Darwin Swift SDK paths used by SwiftPM when the
    /// artifact bundle metadata is present. Older imported runtimes fall back
    /// to xtool's canonical Darwin layout.
    func mobileSwiftSDKConfiguration(
        fileManager: FileManager = .default
    ) throws -> MobileSwiftSDKConfiguration {
        try validate(fileManager: fileManager)

        let fallbackSDK = try iPhoneOSSDK(fileManager: fileManager)
        let fallbackResources = toolchainDirectory
            .appendingPathComponent("usr/lib/swift", isDirectory: true)
        let fallbackPlatformLib = iPhoneOSPlatform
            .appendingPathComponent("Developer/usr/lib", isDirectory: true)

        var sdk = fallbackSDK
        var resources = fallbackResources
        var includePaths = [fallbackPlatformLib]
        var libraryPaths = [fallbackPlatformLib]
        var fromMetadata = false

        if let data = try? Data(contentsOf: swiftSDKMetadataURL),
           let definition = try? JSONDecoder().decode(SwiftSDKDefinition.self, from: data),
           let triple = definition.targetTriples["arm64-apple-ios"]
                ?? definition.targetTriples.first(where: { $0.key.hasPrefix("arm64-apple-ios") })?.value {
            if let value = triple.sdkRootPath {
                sdk = resolvedSwiftSDKPath(value)
            }
            if let value = triple.swiftResourcesPath {
                resources = resolvedSwiftSDKPath(value)
            }
            if let values = triple.includeSearchPaths, !values.isEmpty {
                includePaths = values.map(resolvedSwiftSDKPath)
            }
            if let values = triple.librarySearchPaths, !values.isEmpty {
                libraryPaths = values.map(resolvedSwiftSDKPath)
            }
            fromMetadata = true
        }

        var isDirectory: ObjCBool = false
        guard fileManager.fileExists(atPath: sdk.path, isDirectory: &isDirectory),
              isDirectory.boolValue else {
            throw MobileBuildBackendError.toolchainInvalid(
                "Swift SDK sysroot is missing: \(sdk.path)"
            )
        }
        guard fileManager.fileExists(atPath: resources.path, isDirectory: &isDirectory),
              isDirectory.boolValue else {
            throw MobileBuildBackendError.toolchainInvalid(
                "Swift resource directory is missing: \(resources.path)"
            )
        }

        let iphoneOSResources = resources.appendingPathComponent("iphoneos", isDirectory: true)
        guard fileManager.fileExists(atPath: iphoneOSResources.path, isDirectory: &isDirectory),
              isDirectory.boolValue else {
            throw MobileBuildBackendError.toolchainInvalid(
                "Swift iPhoneOS resources are missing: \(iphoneOSResources.path)"
            )
        }

        let clangHeaders = resources
            .appendingPathComponent("clang/include", isDirectory: true)
        let clangBuiltinHeaders: URL?
        if fileManager.fileExists(
            atPath: clangHeaders.appendingPathComponent("stddef.h").path
        ) || fileManager.fileExists(
            atPath: clangHeaders.appendingPathComponent("stdarg.h").path
        ) {
            clangBuiltinHeaders = clangHeaders
        } else {
            clangBuiltinHeaders = nil
        }

        return MobileSwiftSDKConfiguration(
            sdkURL: sdk,
            swiftResourceDirectory: resources,
            includeSearchPaths: includePaths,
            librarySearchPaths: libraryPaths,
            clangBuiltinHeaders: clangBuiltinHeaders,
            cameFromSwiftSDKMetadata: fromMetadata
        )
    }

    private func resolvedSwiftSDKPath(_ path: String) -> URL {
        if path.hasPrefix("/") {
            return URL(fileURLWithPath: path)
        }
        return root.appendingPathComponent(path)
    }
}

/// A normal Swift/Apple-SDK compile used to graduate from the stdlib-free
/// bootstrap probe to real Foundation/UIKit/SwiftUI compilation.
public struct MobileSwiftSDKImportProbePlan: Sendable, Hashable {
    public let sourceURL: URL
    public let objectURL: URL
    public let configuration: MobileSwiftSDKConfiguration
    public let targetTriple: String
    public let arguments: [String]

    public static func make(
        toolchain: PreparedToolchain,
        workspace: URL,
        deploymentTarget: String = "16.0",
        fileManager: FileManager = .default
    ) throws -> Self {
        let configuration = try toolchain.mobileSwiftSDKConfiguration(
            fileManager: fileManager
        )
        try fileManager.createDirectory(
            at: workspace,
            withIntermediateDirectories: true
        )

        let sdkNamespace = configuration.targetSDKVersion ?? "unknown"
        let runtimeNamespace = PreparedToolchain.expectedBundledRuntimeRevision
        let moduleCache = workspace.appendingPathComponent(
            "ModuleCache-Serialized-\(sdkNamespace)-\(runtimeNamespace)",
            isDirectory: true
        )
        let sdkModuleCache = workspace.appendingPathComponent(
            "SDKModuleCache-Serialized-\(sdkNamespace)-\(runtimeNamespace)",
            isDirectory: true
        )
        try fileManager.createDirectory(
            at: moduleCache,
            withIntermediateDirectories: true
        )
        try fileManager.createDirectory(
            at: sdkModuleCache,
            withIntermediateDirectories: true
        )

        let source = workspace.appendingPathComponent("SDKImports.swift")
        let object = workspace.appendingPathComponent("SDKImports.o")
        let target = "arm64-apple-ios\(deploymentTarget)"

        // Referencing one type from each module forces all three module graphs
        // to load while keeping the probe tiny and independent of app runtime
        // behavior. Unlike the bootstrap probe, this intentionally imports Swift.
        let sourceText = """
        import Foundation
        import UIKit
        import SwiftUI

        public func xtoolSDKImportProbe() {
            _ = NSObject.self
            _ = UIView.self
            _ = Text.self
        }
        """
        try Data(sourceText.utf8).write(to: source, options: .atomic)
        try? fileManager.removeItem(at: object)

        var arguments = [
            "-c",
            "-primary-file", source.path,
            "-target", target,
            "-sdk", configuration.sdkURL.path,
            "-resource-dir", configuration.swiftResourceDirectory.path,
            "-module-cache-path", moduleCache.path,
            "-sdk-module-cache-path", sdkModuleCache.path,
            "-module-name", "XToolSDKImportProbe",
            "-enable-objc-interop",
            "-enable-cross-import-overlays",
            "-disable-modules-validate-system-headers",
            "-Rmodule-loading",
            "-Rmodule-interface-rebuild",
            "-module-load-mode", "prefer-serialized",
            "-I", configuration.iPhoneOSSwiftResourceDirectory.path,
        ]

        if let prebuiltCache = configuration.xtoolPrebuiltModuleCacheDirectory {
            arguments += ["-prebuilt-module-cache-path", prebuiltCache.path]
        }
        if let sdkVersion = configuration.targetSDKVersion {
            arguments += ["-target-sdk-version", sdkVersion]
        }
        if let sdkName = configuration.targetSDKName {
            arguments += ["-target-sdk-name", sdkName]
        }

        for path in configuration.includeSearchPaths {
            arguments += ["-I", path.path]
        }

        // Mirror the C importer setup used by successful non-macOS xtool
        // builds. The SDK sysroot and Swift-sibling Clang headers must agree or
        // Foundation/UIKit can fall back to incompatible host builtin headers.
        arguments += [
            "-Xcc", "-isysroot",
            "-Xcc", configuration.sdkURL.path,
            "-Xcc", "-fmodules-cache-path=\(moduleCache.path)",
        ]
        if let clangHeaders = configuration.clangBuiltinHeaders {
            arguments += [
                "-Xcc", "-isystem",
                "-Xcc", clangHeaders.path,
            ]
        }

        arguments += ["-o", object.path]

        return Self(
            sourceURL: source,
            objectURL: object,
            configuration: configuration,
            targetTriple: target,
            arguments: arguments
        )
    }
}

private struct SwiftSDKDefinition: Decodable {
    let targetTriples: [String: SwiftSDKTriple]
}

private struct SwiftSDKTriple: Decodable {
    let sdkRootPath: String?
    let includeSearchPaths: [String]?
    let librarySearchPaths: [String]?
    let swiftResourcesPath: String?
}
